-- ============================================================
--  ASIS Oracle DDL  -  KS銀行 ミニバンク・デモ  (전 컬럼 RAW)
--  ★ 이 파일은 라이브 서버 DB(전 컬럼 EBCDIC/COMP-3/존10진 RAW 통일 상태)에서
--     DBMS_METADATA로 재생성한 정본입니다. (2026-07-29)
--     텍스트=JEF EBCDIC, 금액=COMP-3, 키=존10진 EBCDIC 모두 RAW로 저장.
--     예외: KOUZA_EXT.KANJI_UTF8/KANA_UTF8(조회용 UTF-8 미러) + V_* 디코드 뷰.
--  실행순: 01_ddl.sql -> 02_seed.sql
-- ============================================================

-- gvenzl은 initdb.d를 SYSTEM으로 실행하므로 명시적으로 minibank에 접속.
CONNECT minibank/minibank@//localhost:1521/FREEPDB1

-- ------------------------------------------------------------
--  재실행 가능하도록 기존 오브젝트 제거
-- ------------------------------------------------------------
BEGIN
  FOR v IN (SELECT view_name FROM user_views) LOOP
    EXECUTE IMMEDIATE 'DROP VIEW '||v.view_name;
  END LOOP;
  FOR t IN (SELECT table_name FROM user_tables) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE '||t.table_name||' CASCADE CONSTRAINTS PURGE';
  END LOOP;
  FOR s IN (SELECT sequence_name FROM user_sequences) LOOP
    EXECUTE IMMEDIATE 'DROP SEQUENCE '||s.sequence_name;
  END LOOP;
END;
/

-- ---------------- 테이블 (부모 먼저) ----------------
CREATE TABLE "BANK_ASIS" 
   (	"BANK_ID" RAW(4), 
	"NAME" RAW(84) NOT NULL ENABLE, 
	"COLOR" RAW(9), 
	"TEXT_COLOR" RAW(9), 
	"MARK" RAW(20), 
	 CONSTRAINT "PK_BANK_ASIS" PRIMARY KEY ("BANK_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_BANK_ASIS" UNIQUE ("NAME")
  USING INDEX  ENABLE
   );

CREATE TABLE "BRANCH_ASIS" 
   (	"BRANCH_CODE" RAW(3), 
	"NAME_JA" RAW(84) NOT NULL ENABLE, 
	 CONSTRAINT "PK_BRANCH_ASIS" PRIMARY KEY ("BRANCH_CODE")
  USING INDEX  ENABLE
   );

CREATE TABLE "NOTICE_ASIS" 
   (	"NOTICE_ID" RAW(12), 
	"NOTICE_DATE" RAW(8) NOT NULL ENABLE, 
	"TAG" RAW(60), 
	"TITLE" RAW(600) NOT NULL ENABLE, 
	"BODY" RAW(2000), 
	"IS_ACTIVE" RAW(1) NOT NULL ENABLE, 
	 CONSTRAINT "PK_NOTICE_ASIS" PRIMARY KEY ("NOTICE_ID")
  USING INDEX  ENABLE
   );

CREATE TABLE "NOTICE_FILE_ASIS" 
   (	"FILE_ID" RAW(15), 
	"NOTICE_ID" RAW(12), 
	"FILE_NAME" RAW(600) NOT NULL ENABLE, 
	 CONSTRAINT "PK_NOTICE_FILE_ASIS" PRIMARY KEY ("FILE_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_NOTICE_FILE_ASIS" FOREIGN KEY ("NOTICE_ID")
	  REFERENCES "NOTICE_ASIS" ("NOTICE_ID") ON DELETE CASCADE ENABLE
   );

CREATE TABLE "KOUZA" 
   (	"KOUZA_NO" RAW(7), 
	"MEIGI_KANJI" RAW(20) NOT NULL ENABLE, 
	"MEIGI_KANA" RAW(20) NOT NULL ENABLE, 
	"SHUBETSU" RAW(1) NOT NULL ENABLE, 
	"KAISETSU_BI" RAW(8) NOT NULL ENABLE, 
	"JOUTAI" RAW(1) NOT NULL ENABLE, 
	"ZANDAKA" RAW(6), 
	 CONSTRAINT "PK_KOUZA" PRIMARY KEY ("KOUZA_NO")
  USING INDEX  ENABLE
   );

CREATE TABLE "KOUZA_EXT" 
   (	"KOUZA_NO" RAW(7), 
	"BRANCH_CODE" RAW(3) NOT NULL ENABLE, 
	"ACCT_TYPE" RAW(12) NOT NULL ENABLE, 
	"PASSWORD" RAW(60), 
	"IS_PRIMARY" RAW(1) NOT NULL ENABLE, 
	"SAVE_TERM" RAW(3), 
	"SAVE_MONTHLY" RAW(8), 
	"KANJI_UTF8" NVARCHAR2(60), 
	"KANA_UTF8" NVARCHAR2(60), 
	"BIRTH" RAW(10), 
	"SEX" RAW(12), 
	"ZIP" RAW(7), 
	"ADDR" RAW(200), 
	"PHONE" RAW(13), 
	"EMAIL" RAW(120), 
	"JOB" RAW(40), 
	 CONSTRAINT "PK_KOUZA_EXT" PRIMARY KEY ("KOUZA_NO")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_KOUZA_EXT" FOREIGN KEY ("KOUZA_NO")
	  REFERENCES "KOUZA" ("KOUZA_NO") ENABLE
   );

CREATE TABLE "TORIHIKI" 
   (	"TORIHIKI_ID" RAW(12), 
	"KOUZA_NO" RAW(7), 
	"TORIHIKI_DT" RAW(14) NOT NULL ENABLE, 
	"TORIHIKI_KBN" RAW(1) NOT NULL ENABLE, 
	"KINGAKU" RAW(6), 
	"AITE_KOUZA" RAW(7), 
	"TESURYO" RAW(3), 
	"TEKIYOU" RAW(40), 
	 CONSTRAINT "PK_TORIHIKI" PRIMARY KEY ("TORIHIKI_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_TORIHIKI_KZ" FOREIGN KEY ("KOUZA_NO")
	  REFERENCES "KOUZA" ("KOUZA_NO") ENABLE
   );

CREATE TABLE "LOAN_ASIS" 
   (	"LOAN_ID" RAW(12), 
	"KOUZA_NO" RAW(7), 
	"PRINCIPAL" RAW(6), 
	"BALANCE" RAW(6), 
	"METHOD" RAW(1) NOT NULL ENABLE, 
	"TERM_YEARS" RAW(2), 
	"RATE" RAW(4), 
	"STATUS" RAW(10) NOT NULL ENABLE, 
	"OPENED_DATE" RAW(8), 
	"CLOSED_DATE" RAW(8), 
	 CONSTRAINT "PK_LOAN_ASIS" PRIMARY KEY ("LOAN_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_LOAN_ASIS" FOREIGN KEY ("KOUZA_NO")
	  REFERENCES "KOUZA" ("KOUZA_NO") ENABLE
   );

CREATE TABLE "LOAN_REPAY_ASIS" 
   (	"REPAY_ID" RAW(15), 
	"LOAN_ID" RAW(12), 
	"PRINCIPAL" RAW(6), 
	"INTEREST" RAW(6), 
	"FEE" RAW(6), 
	"TOTAL" RAW(6), 
	"REPAY_DATE" RAW(8), 
	"RECEIPT_NO" RAW(30), 
	 CONSTRAINT "PK_REPAY_ASIS" PRIMARY KEY ("REPAY_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_REPAY_ASIS" FOREIGN KEY ("LOAN_ID")
	  REFERENCES "LOAN_ASIS" ("LOAN_ID") ENABLE
   );

-- ---------------- 보조 인덱스 ----------------

-- ---------------- 시퀀스 (현재 채번값 보존) ----------------
CREATE SEQUENCE  "SEQ_KOUZA_DYN"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 9000001 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
CREATE SEQUENCE  "SEQ_TORIHIKI"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 100000000001 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
CREATE SEQUENCE  "SEQ_LOAN_ASIS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
CREATE SEQUENCE  "SEQ_REPAY_ASIS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
CREATE SEQUENCE  "SEQ_NOTICE_ASIS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
CREATE SEQUENCE  "SEQ_RECEIPT_ASIS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10251 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;

-- ---------------- 디코드 함수 (뷰용) ----------------
CREATE OR REPLACE EDITIONABLE FUNCTION "FN_UNZONE" (r RAW) RETURN NUMBER IS
BEGIN
  IF r IS NULL THEN RETURN NULL; END IF;
  RETURN TO_NUMBER(REPLACE(RAWTOHEX(r),'F',''));
END;
/

CREATE OR REPLACE EDITIONABLE FUNCTION "FN_UNPACK" (r RAW) RETURN NUMBER IS
  h VARCHAR2(64);
BEGIN
  IF r IS NULL THEN RETURN NULL; END IF;
  h := RAWTOHEX(r);
  RETURN TO_NUMBER(SUBSTR(h,1,LENGTH(h)-1)) * CASE WHEN SUBSTR(h,-1)='D' THEN -1 ELSE 1 END;
END;
/

CREATE OR REPLACE EDITIONABLE FUNCTION "FN_EBC" (r RAW) RETURN VARCHAR2 IS
BEGIN
  IF r IS NULL THEN RETURN NULL; END IF;
  RETURN UTL_I18N.RAW_TO_CHAR(r, 'WE8EBCDIC500');
END;
/

CREATE OR REPLACE EDITIONABLE FUNCTION "KANA2EBC" (p IN NVARCHAR2) RETURN RAW IS
  v_ref NVARCHAR2(100) :=
    N'アイウエオカキクケコサシスセソタチツテトナニヌネノハヒフヘホマミムメモヤユヨラリルレロワヲン';
  v_src NVARCHAR2(60);
  v_out RAW(20);
  v_ch  NVARCHAR2(1);
  v_idx PLS_INTEGER;
  v_b   PLS_INTEGER;
BEGIN
  -- 濁音・半濁音は清音へ寄せる(デモ用)
  v_src := TRANSLATE(p,
    N'ガギグゲゴザジズゼゾダヂヅデドバビブベボパピプペポ',
    N'カキクケコサシスセソタチツテトハヒフヘホハヒフヘホ');
  v_out := UTL_RAW.CAST_TO_RAW('');
  FOR i IN 1 .. LEAST(NVL(LENGTH(v_src),0), 20) LOOP
    v_ch  := SUBSTR(v_src, i, 1);
    v_idx := INSTR(v_ref, v_ch);
    IF v_idx = 0 THEN v_b := 64; ELSE v_b := 65 + v_idx; END IF;  -- 0x41+idx
    v_out := UTL_RAW.CONCAT(v_out, UTL_RAW.SUBSTR(UTL_RAW.CAST_TO_RAW(CHR(v_b)), 1, 1));
  END LOOP;
  -- 20byte まで EBCDIC 空白(0x40)でパディング
  WHILE UTL_RAW.LENGTH(v_out) < 20 LOOP
    v_out := UTL_RAW.CONCAT(v_out, HEXTORAW('40'));
  END LOOP;
  RETURN UTL_RAW.SUBSTR(v_out, 1, 20);
END;
/

CREATE OR REPLACE EDITIONABLE FUNCTION "KANJI2EBC" (p IN NVARCHAR2) RETURN RAW IS
  v_out RAW(30);
  v_n   PLS_INTEGER;
  v_hi  PLS_INTEGER;
  v_lo  PLS_INTEGER;
BEGIN
  -- SO(0x0E) で DBCS 開始
  v_out := HEXTORAW('0E');
  v_n := NVL(LENGTH(p), 0);
  FOR i IN 1 .. v_n LOOP
    -- プレースホルダ DBCS 2byte(実バイトはエンコーダ確定後に差替)
    v_hi := 66 + MOD(i, 20);          -- 0x42..
    v_lo := 66 + MOD(i * 3, 20);
    v_out := UTL_RAW.CONCAT(v_out,
               UTL_RAW.CONCAT(UTL_RAW.SUBSTR(UTL_RAW.CAST_TO_RAW(CHR(v_hi)),1,1),
                              UTL_RAW.SUBSTR(UTL_RAW.CAST_TO_RAW(CHR(v_lo)),1,1)));
  END LOOP;
  -- SI(0x0F) で SBCS へ戻す
  v_out := UTL_RAW.CONCAT(v_out, HEXTORAW('0F'));
  -- 空白(0x40)パディング
  WHILE UTL_RAW.LENGTH(v_out) < 20 LOOP
    v_out := UTL_RAW.CONCAT(v_out, HEXTORAW('40'));
  END LOOP;
  -- ★結定打3★ X(20) の 20byte 境界で切り詰め(SO/SI 含む)
  RETURN UTL_RAW.SUBSTR(v_out, 1, 20);
END;
/

-- ---------------- 조회용 디코드 뷰 ----------------
CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_KOUZA" ("KOUZA_NO", "MEIGI_KANJI", "MEIGI_KANA", "SHUBETSU", "KAISETSU_BI", "JOUTAI", "ZANDAKA", "BRANCH_CODE") AS 
  SELECT FN_UNZONE(k.KOUZA_NO) KOUZA_NO, e.KANJI_UTF8 MEIGI_KANJI, e.KANA_UTF8 MEIGI_KANA,
       FN_EBC(k.SHUBETSU) SHUBETSU, FN_EBC(k.KAISETSU_BI) KAISETSU_BI, FN_EBC(k.JOUTAI) JOUTAI,
       FN_UNPACK(k.ZANDAKA) ZANDAKA, FN_EBC(e.BRANCH_CODE) BRANCH_CODE
FROM KOUZA k JOIN KOUZA_EXT e ON e.KOUZA_NO=k.KOUZA_NO
/

CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_TORIHIKI" ("TORIHIKI_ID", "KOUZA_NO", "TORIHIKI_DT", "TORIHIKI_KBN", "KINGAKU", "AITE_KOUZA", "TESURYO") AS 
  SELECT FN_UNZONE(TORIHIKI_ID) TORIHIKI_ID, FN_UNZONE(KOUZA_NO) KOUZA_NO,
       FN_EBC(TORIHIKI_DT) TORIHIKI_DT, FN_EBC(TORIHIKI_KBN) TORIHIKI_KBN,
       FN_UNPACK(KINGAKU) KINGAKU, FN_UNZONE(AITE_KOUZA) AITE_KOUZA, FN_UNPACK(TESURYO) TESURYO
FROM TORIHIKI
/

CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_LOAN" ("LOAN_ID", "KOUZA_NO", "PRINCIPAL", "BALANCE", "METHOD", "TERM_YEARS", "RATE", "STATUS", "OPENED_DATE", "CLOSED_DATE") AS 
  SELECT FN_UNZONE(LOAN_ID) LOAN_ID, FN_UNZONE(KOUZA_NO) KOUZA_NO,
       FN_UNPACK(PRINCIPAL) PRINCIPAL, FN_UNPACK(BALANCE) BALANCE, FN_EBC(METHOD) METHOD,
       FN_UNPACK(TERM_YEARS) TERM_YEARS, FN_UNPACK(RATE)/1000 RATE, FN_EBC(STATUS) STATUS,
       FN_EBC(OPENED_DATE) OPENED_DATE, FN_EBC(CLOSED_DATE) CLOSED_DATE
FROM LOAN_ASIS
/

CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_REPAY" ("REPAY_ID", "LOAN_ID", "PRINCIPAL", "INTEREST", "FEE", "TOTAL", "REPAY_DATE", "RECEIPT_NO") AS 
  SELECT FN_UNZONE(REPAY_ID) REPAY_ID, FN_UNZONE(LOAN_ID) LOAN_ID, FN_UNPACK(PRINCIPAL) PRINCIPAL,
       FN_UNPACK(INTEREST) INTEREST, FN_UNPACK(FEE) FEE, FN_UNPACK(TOTAL) TOTAL,
       FN_EBC(REPAY_DATE) REPAY_DATE, FN_EBC(RECEIPT_NO) RECEIPT_NO
FROM LOAN_REPAY_ASIS
/

CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_NOTICE" ("NOTICE_ID", "NOTICE_DATE", "IS_ACTIVE", "TITLE_JEF_RAW") AS 
  SELECT FN_UNZONE(NOTICE_ID) NOTICE_ID, FN_EBC(NOTICE_DATE) NOTICE_DATE,
       FN_EBC(IS_ACTIVE) IS_ACTIVE, RAWTOHEX(TITLE) TITLE_JEF_RAW
FROM NOTICE_ASIS
/

COMMIT;
